# Generated by Django 4.2.1 on 2023-07-24 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0004_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_file', models.FileField(upload_to='course_files')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('course_image', models.ImageField(blank=True, upload_to='course_images')),
                ('course_tag', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='', max_length=100, null=True)),
                ('course_video', models.CharField(blank=True, max_length=1000)),
                ('course_files', models.ManyToManyField(blank=True, to='EdGeniusApp.coursefile')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeItem', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('feedback', models.TextField(blank=True, max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('attendance', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.student')),
            ],
        ),
    ]
