# Generated by Django 4.2.1 on 2023-07-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0005_attendance_courseenrolled_coursefile_courses_grades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
    ]
