# Generated by Django 4.2.1 on 2023-07-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0006_remove_courses_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_files',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_image',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_tag',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_video',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='slug',
        ),
    ]
