# Generated by Django 4.2.2 on 2023-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                ("courseName", models.CharField(max_length=100)),
                ("course_id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=1000)),
                (
                    "course_image",
                    models.ImageField(blank=True, upload_to="course_images"),
                ),
                ("course_tag", models.CharField(max_length=100)),
            ],
        ),
    ]
