# Generated by Django 4.2.2 on 2023-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EdGeniusApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="course_pdf",
            field=models.FileField(blank=True, upload_to="course_pdfs"),
        ),
    ]
