# Generated by Django 4.1 on 2023-07-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0002_courses_course_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='courseName',
            new_name='CourseName',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_id',
            new_name='courseID',
        ),
    ]
