# Generated by Django 4.1 on 2023-07-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0003_rename_coursename_courses_coursename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilverTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='GoldTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='BronzeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.courses')),
            ],
        ),
    ]
