# Generated by Django 4.1 on 2023-07-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0005_instructor_courses_instructorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True),
        ),
    ]
