# Generated by Django 4.1 on 2023-07-21 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0006_courses_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_pdf',
        ),
    ]
