# Generated by Django 4.1 on 2023-07-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0007_remove_courses_course_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_pdf',
            field=models.FileField(blank=True, upload_to='course_pdfs'),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_video',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
