# Generated by Django 4.1 on 2023-07-23 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0008_courses_course_pdf_courses_course_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_pdf',
        ),
        migrations.CreateModel(
            name='CourseMaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_pdf', models.FileField(blank=True, upload_to='course_pdfs')),
                ('course_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdGeniusApp.coursematerial')),
            ],
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='files',
            field=models.ManyToManyField(to='EdGeniusApp.coursematerialfile'),
        ),
    ]
