# Generated by Django 4.1 on 2023-07-23 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0009_coursematerial_remove_courses_course_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_file', models.FileField(upload_to='course_files')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='EdGeniusApp.courses')),
            ],
        ),
        migrations.RemoveField(
            model_name='coursematerialfile',
            name='course_material',
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
        migrations.DeleteModel(
            name='CourseMaterialFile',
        ),
    ]
