# Generated by Django 4.1 on 2023-07-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0010_coursefile_remove_coursematerialfile_course_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
