# Generated by Django 4.1 on 2023-07-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0011_coursefile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_files',
            field=models.FileField(blank=True, upload_to='course_files'),
        ),
        migrations.DeleteModel(
            name='CourseFile',
        ),
    ]
