# Generated by Django 4.1 on 2023-07-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdGeniusApp', '0012_courses_course_files_delete_coursefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_file', models.FileField(upload_to='course_files')),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_files',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_files',
            field=models.ManyToManyField(blank=True, to='EdGeniusApp.coursefile'),
        ),
    ]
